--liquibase formatted sql

--changeset mikhail:1
CREATE TABLE IF NOT EXISTS USERS
(
    ID BIGINT,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE SEQUENCE USERS_SEC START WITH 1;

CREATE TABLE IF NOT EXISTS ACCOUNT
(
    ID BIGINT,
    ACCOUNT_NUMBER BIGINT NOT NULL UNIQUE,
    USER_ID BIGINT,
    FOREIGN KEY (USER_ID) REFERENCES USERS (ID),
    PRIMARY KEY (ID)
);

CREATE SEQUENCE ACCOUNT_SEC START WITH 1;